apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd
spec:
  sourceRepos:
  - "https://github.com/rosvali/raguillo-argocd"
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
