Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  NODES = [
    { :hostname => "raguilloS", :ip => "192.168.42.110", :cpus => 1, :memory => 512, :path => "server.sh"},
    { :hostname => "raguilloSW", :ip => "192.168.42.111", :cpus => 1, :memory => 512, :path => "server_worker.sh"}
  ]

  NODES.each do |node|
    config.vm.define node[:hostname] do |config|
      config.vm.hostname = node[:hostname]
      config.vm.network "private_network", ip: node[:ip]

      config.vm.provider "virtualbox" do |v|
        v.name = node[:hostname]
        v.cpus = node[:cpus]
        v.memory = node[:memory]
      end

      config.vm.provision "shell", privileged: true, path: node[:path]
      config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    end
  end
end
