Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_url = "https://app.vagrantup.com/centos/boxes/stream8/versions/20210210.0/providers/virtualbox.box"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  NODES = [
    { :hostname => "gitlabvm", :ip => "192.168.42.100", :cpus => 4, :memory => 4096, :spath =>  "scripts/install.sh"}
  ]

  NODES.each do |node|
    config.vm.define node[:hostname] do |config|
      config.vm.network "forwarded_port", guest: 8181, host: 8181, protocol: "tcp"
      config.vm.hostname = node[:hostname]
      config.vm.network "private_network", ip: node[:ip], hostname: true
      config.vm.synced_folder ".", "/vagrant", type: "virtualbox", SharedFoldersEnableSymlinksCreate: true

      config.vm.provider "virtualbox" do |vb|
        vb.name = node[:hostname]
        vb.cpus = node[:cpus]
        vb.memory = node[:memory]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      config.vm.provision "shell", path: node[:spath], privileged: true, args: node[:ip]
    end
  end
end